// src/app/layout.tsx
import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import "./globals.css";
import { ClientProviderNoSSR } from './components/ClientProvider';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "FIGMA",
  description: "Generated by create next app",
  metadataBase: new URL('https://your-site.com'),
  alternates: {
    canonical: '/',
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
  },
  verification: {
    google: 'google-site-verification-code',
  },
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    type: 'website',
    title: 'Elite Mart',
    description: 'Your ecommerce destination',
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ClientProviderNoSSR>
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
        </ClientProviderNoSSR>
      </body>
    </html>
  );
}
