import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import "./globals.css";
import { ClientProviderNoSSR } from './components/ClientProvider';
import { CartProvider } from './context/CartContext';
import { Toaster } from 'react-hot-toast';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Elite Mart",
  description: "Generated by create next app",
  metadataBase: new URL('https://your-site.com'),
  alternates: {
    canonical: '/',
  },
  verification: {
    google: 'google-site-verification-code',
  },
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    type: 'website',
    title: 'Elite Mart',
    description: 'Your ecommerce destination',
  }
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <CartProvider>
          <ClientProviderNoSSR>
            <Navbar />
            <main className="flex-grow">{children}</main>
            <Footer />
            <Toaster
              position="bottom-right"
              toastOptions={{
                duration: 2000,
                style: {
                  background: '#363636',
                  color: '#fff',
                },
                success: {
                  duration: 2000,
                  style: {
                    background: '#22c55e',
                  },
                },
                error: {
                  duration: 2000,
                  style: {
                    background: '#ef4444',
                  },
                },
              }}
            />
          </ClientProviderNoSSR>
        </CartProvider>
      </body>
    </html>
  );
}
